/**
 * Interface for application storage providers.
 * 
 * Invariants:
 * 1. Keys are generated by the application (e.g., UUIDs, hashes), not derived from arbitrary user input.
 * 2. The provider is agnostic to the underlying storage mechanism (no coupling to Node.js `fs` or specific cloud SDKs in the interface).
 * 3. The provider is not responsible for validating content types, malware scanning, or file size limits (this must be done before saving).
 * 4. Delete operations must be idempotent (should not fail if the key does not exist).
 * 5. Methods should throw clear errors for failures like connection issues or missing files on read.
 */
export interface StorageProvider {
  /**
   * Saves the provided data to storage using the given key.
   * If the key already exists, it will be overwritten.
   * 
   * @param key Application-generated unique identifier
   * @param data The content to store
   * @param contentType Optional MIME type of the content
   */
  save(key: string, data: Buffer | Uint8Array | string, contentType?: string): Promise<void>;

  /**
   * Reads the content from storage.
   * 
   * @param key The unique identifier of the stored content
   * @returns The content as a Buffer
   * @throws Error if the key is not found
   */
  read(key: string): Promise<Buffer>;

  /**
   * Deletes the content associated with the key.
   * Must be idempotent (do nothing if key doesn't exist).
   * 
   * @param key The unique identifier of the stored content
   */
  delete(key: string): Promise<void>;

  /**
   * Generates a reference (e.g., URL or path string) to access the stored content.
   * This might be a signed URL in cloud storage or a local static route path.
   * 
   * @param key The unique identifier of the stored content
   * @returns An access reference string
   */
  getAccessReference(key: string): Promise<string>;
}
